version: "3.9"

services:
  web:
    build: .
    container_name: upload-img-dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:secret@db:5432/image
      NODE_ENV: development
    volumes:
      - .:/app              # sinkronisasi file lokal ↔ container
      - /app/node_modules   # cegah node_modules host menimpa container
      - uploads_data:/app/uploads
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:alpine
    container_name: image-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: image
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
  uploads_data:

networks:
  app-network:
    driver: bridge
